import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Dimensions,
  View,
  Share,
  ActivityIndicator
} from 'react-native';

import axios from 'axios';
import * as SecureStore from 'expo-secure-store';

import { connect } from 'react-redux';

import CustomText from '../../../custom/CustomText';
import CustomLayout from '../../../custom/CustomLayout';
import CustomButton from '../../../custom/CustomButton';
import Divider from '../../../custom/Divider';

export const { width, height } = Dimensions.get('window');
import QRCode from 'react-native-qrcode-svg';

import useMenuUrl from '../../../customHooks/createMenuUrl';

import Color from '../../../constants/Color';
import { URL } from '../../../constants/variables';

import { IUserType } from '../../../types/user.types';

interface Props {
  user: IUserType;
}

const styles = StyleSheet.create({
  layout: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height
  },
  text: {
    fontSize: 20,
    color: 'white',
    width: width * 0.8,
    textAlign: 'center',
    marginBottom: 10
  },
  text1: {
    fontSize: 16,
    color: Color.tertiary,
    width: width * 0.8,
    textAlign: 'center',
    marginBottom: 10
  },
  text2: {
    fontSize: 14,
    color: Color.primary,
    width: width * 0.8,
    textAlign: 'center',
    marginBottom: 10
  }
});

const QRcodeScreen: React.FC<Props> = ({ user }) => {
  const [svg, setSvg] = useState<any>();
  const [urlProvider, setUrlProvider] = useState<string>('');

  const url = useMenuUrl(user);

  useEffect(() => {
    writeMenuUrl();
  }, [urlProvider]);

  // console.log('url provideeeeer', urlProvider);
  // if (!url) {
  //   return (
  //     <CustomLayout style={styles.layout}>
  //       <CustomText type="extra-bold" style={styles.text}>
  //         Creating Url
  //       </CustomText>
  //       <Divider />
  //       <ActivityIndicator size="large" />
  //     </CustomLayout>
  //   );
  // }

  url.then((res: any) => setUrlProvider(res));

  const getDataURL = () => {
    svg.toDataURL(callback);
  };

  const callback = (dataURL: any) => {
    let shareImageBase64 = {
      title: 'Your Qr Code',
      message:
        'Here you have your QR Code generated by Social Coffee App! You can save it, share it with your clients or send it to you by email!',
      url: `data:image/png;base64,${dataURL}`,
      subject: 'Here you have your QR Code generated by Social Coffee App' //  for email
    };
    Share.share(shareImageBase64).catch(error => console.log(error));
  };

  const writeMenuUrl = async () => {
    const token = await SecureStore.getItemAsync('jwt');

    const data = { urlProvider };

    try {
      const axiosInstance = await axios.create({
        baseURL: `${URL}/api/v1/provider/writeUrl`,
        headers: {
          Authorization: `Bearer ${token}`,
          'Access-Control-Allow-Origin': '*'
        },
        timeout: 6000
      });

      const response = await axiosInstance({
        method: 'PATCH',
        data
      });

      console.log(response.data.data);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <React.Fragment>
      <CustomLayout style={styles.layout}>
        <CustomText type="extra-bold" style={styles.text}>
          Here is your URL:
        </CustomText>
        <CustomText type="light" style={styles.text2}>
          At this URL your clients will find the menu you upload on this app any
          time you want!
        </CustomText>
        <CustomText type="extra-bold" style={styles.text1}>
          {urlProvider}
        </CustomText>
        <Divider />

        <CustomText type="extra-bold" style={styles.text}>
          And here is your generated QR Code
        </CustomText>
        <Divider style={{ marginBottom: 30, marginTop: 30 }} />
        <QRCode
          value={
            !!urlProvider
              ? JSON.stringify({ urlProvider })
              : 'https://some-default-url.com'
          }
          getRef={c => setSvg(c)}
          size={200}
        />

        <View style={{ marginTop: 40 }}>
          <CustomButton
            buttonWidth="60%"
            name="account-heart-outline"
            size={18}
            color="cyan"
            fontSize={12}
            textType="bold"
            text="Share your Qr Code"
            onPress={getDataURL}
          />
        </View>
      </CustomLayout>
    </React.Fragment>
  );
};

const mapStateToProps = ({ user }: any) => ({
  user: user.user
});

export default connect(mapStateToProps)(QRcodeScreen);
