export enum IUsersTypes {
    START_GET_USER = 'START_GET_USER',
    SUCCESS_USER_GET = 'SUCCESS_USER_GET',
    FAILURE_USER_GET = 'FAILURE_USER_GET',
    SUCCESS_PROVIDER_GET = 'SUCCESS_PROVIDER_GET',
    FAILURE_PROVIDER_GET = 'FAILURE_PROVIDER_GET'
}
