export enum IUsersTypes {
    //Get user on app open
    START_GET_USER = 'START_GET_USER',
    // reducer action types
    SUCCESS_USER_GET = 'SUCCESS_USER_GET',
    FAILURE_USER_GET = 'FAILURE_USER_GET',
    //Login Types
    START_LOGIN_USER = 'START_SIGNUP_USER',
    START_LOGIN_PROVIDER = 'START_SIGNUP_PROVIDER',
    //SignupTypes
    START_SIGNUP_USER = 'START_SIGNUP_USER',
    START_SIGNUP_PROVIDER = 'START_SIGNUP_PROVIDER', 
}
