export enum IUsersTypes {
  //Get user on app open
  START_GET_USER = 'START_GET_USER',
  SUCCESS_USER_GET = 'SUCCESS_USER_GET',
  FAILURE_USER_GET = 'FAILURE_USER_GET',
  //Login Types
  START_LOGIN_USER = 'START_LOGIN_USER',
  START_LOGIN_PROVIDER = 'START_LOGIN_PROVIDER',
  SUCCESS_LOGIN = 'SUCCESS_LOGIN',
  FAILURE_LOGIN = 'FAILURE_LOGIN',
  //SignupTypes
  START_SIGNUP_USER = 'START_SIGNUP_USER',
  START_SIGNUP_PROVIDER = 'START_SIGNUP_PROVIDER',
  SUCCESS_SIGNUP = 'SUCCESS_SIGNUP',
  FAILURE_SIGNUP = 'FAILURE_SIGNUP',
  // clean errors
  CLEAN_ERRORS = 'CLEAN_ERRORS',
  //reset password
  START_RESET_PASSWORD = 'START_RESET_PASSWORD',
  SUCCESS_RESET_PASSWORD = 'SUCCESS_RESET_PASSWORD',
  FAILURE_RESET_PASSWORD = 'FAILURE_RESET_PASSWORD'
}
